<a href="https://colab.research.google.com/github/dursus/2026-NYC-20-DBoucard/blob/main/David_Boucard_PA_386_2_1_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PA 386.2.1: Practice Assignment—NumPy**


##**Introduction:**
NumPy (Numerical Python) is a fundamental Python library for numerical and scientific computing. It provides support for arrays and matrices, as well as a wide range of mathematical functions to work with them efficiently.
This practice assignment introduces the basics of NumPy, including data type objects, one-dimensional and multidimensional arrays, the relationship between NumPy arrays and DataFrames, and common NumPy operations.

##**Objectives:**
By completing this assignment, I will:
* Recognize the importance of NumPy in scientific computing.
* Experiment with data type objects and how they are used in NumPy.
* Operate one-dimensional and multidimensional arrays.

##**Prerequisite/Equipment**
* Python environment.
* Python-related IDE (e.g., Anaconda, Jupyter Notebook).
* NumPy library installed (can be installed via pip or conda).



##**Instructions**
**Task 1: Data Type Objects in NumPy**
1. Create a NumPy array using np.array() function and specify the data type as 'int32.' Print the array and its data type.
2. Create another NumPy array using np.array() with the data type as 'float64.' Print the array and its data type.




In [1]:
import numpy as np

# Create a NumPy array with 32-bit integers
int_array = np.array([1, 2, 3], dtype='int32')
print(int_array)
print(int_array.dtype)

# Create a NumPy array with 64-bit floats
float_array = np.array([1.0, 2.0, 3.0], dtype='float64')
print(float_array)
print(float_array.dtype)

[1 2 3]
int32
[1. 2. 3.]
float64


**Task 2: One-Dimensional**
1. Create a one-dimensional NumPy array containing the integers from 1 to 5. Print the array.


In [2]:
import numpy as np

# Create a NumPy array with integers 1 to 5
one_dim_array = np.array([1, 2, 3, 4, 5])
print(one_dim_array)

[1 2 3 4 5]


**Task 3: NumPy Operations**
1. Create two NumPy arrays, arr1 and arr2, with any value of your choice. Perform element-wise addition, subtraction, multiplication, and division between these arrays and print the results.
2. Calculate the dot product between arr1 and arr2. Print the result.
3. Use NumPy to calculate the mean, median, and standard deviation of arr1.


In [3]:
import numpy as np

# Create two sample NumPy arrays to perform calculations
arr1 = np.array([12, 25, 42, 16, 32])
arr2 = np.array([4, 5, 6, 8, 8])

# Add, substract, multiply, and divide the two arrays
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

# Find the dot product
# (arr1[0]*arr2[0]) + (arr1[1]*arr2[1]) + (arr1[2]*arr2[2])...
print(np.dot(arr1, arr2))

# Find the mean, median, and standard deviation of the first array
print(np.mean(arr1))
print(np.median(arr1))
print(np.std(arr1))

[16 30 48 24 40]
[ 8 20 36  8 24]
[ 48 125 252 128 256]
[3. 5. 7. 2. 4.]
809
25.4
25.0
10.836973747315254
